## Подготовка данных для SQL запроса на добавление

### Подготовка nomenclature

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/home/fusion/project/serx/serx/parser/data/nomenclature.csv", sep="~")
df

   Код номенклатуры                                       Номенклатура
0            313273  Мороженое пломбир с ароматом ванили м.д.ж. 15%...
1                57                         Тушка ЦБ 1 сорта пакет г/я
2            257245  Микс ЦБ (Плечевая часть крыла, локтевая часть ...
3            269705     Микс ЦБ: (Бедро, голень) вес лоток г/я 6кг Охл
4            236411  Микс ЦБ: (Бедро, голень) лоток 1,5 кг г/я 12 к...
5              1168                    Бедро ЦБ вес лоток г/я 6 кг Зам
6              1170           Большое филе ЦБ вес лоток г/я 6,8 кг Зам
7            335615      Сосиски Нежные Свиные в/с вес т/ф газ г/я Охл
8            286763  Колбаски Кабаносы в/к в/с т/ф 0,55кг г/я 3,3кг...
9            296732  Колбаса Сервелат с сыром в/к в/с т/ф вак 0,36к...

In [3]:
for i in range(len(df)):
    print(f"({df.iloc[i][0]}, '{df.iloc[i][1]}'),")

(313273, 'Мороженое пломбир с ароматом ванили м.д.ж. 15% 0,07кг г/я 3,36кг (МФМ) Зам'),
(57, 'Тушка ЦБ 1 сорта пакет г/я'),
(257245, 'Микс ЦБ (Плечевая часть крыла, локтевая часть крыла) вес лоток г/я 12кг Зам'),
(269705, 'Микс ЦБ: (Бедро, голень) вес лоток г/я 6кг Охл'),
(236411, 'Микс ЦБ: (Бедро, голень) лоток 1,5 кг г/я 12 кг Зам'),
(1168, 'Бедро ЦБ вес лоток г/я 6 кг Зам'),
(1170, 'Большое филе ЦБ вес лоток г/я 6,8 кг Зам'),
(335615, 'Сосиски Нежные Свиные в/с вес т/ф газ г/я Охл'),
(286763, 'Колбаски Кабаносы в/к в/с т/ф 0,55кг г/я 3,3кг (РФ) Охл'),
(296732, 'Колбаса Сервелат с сыром в/к в/с т/ф вак 0,36кг г/я 2,88кг (РФ) Охл'),

### Подготовка marketplace

In [65]:
place = pd.read_csv(
    "/home/fusion/project/serx/serx/parser/data/place.csv",
    sep="~",
)
place

,Магазин,Адрес,Регион,Область,Широта,Долгота
0,"""Минская обл, Воложин г., Советская ул., д. 9...",NaN,NaN,NaN,NaN,NaN
1,"""Минск г., Пушкина пр., д. 3А, магазин """"Евроо...",NaN,NaN,NaN,NaN,NaN
2,"""Минск г., Ольшевского ул., дом № 20 пом.2, ма...",NaN,NaN,NaN,NaN,NaN
3,"Витебская обл, Орша г., Ленина ул., дом № 230Ю...","Витебская обл, Орша г., Ленина ул., дом № 230Ю",Орша г.,ВИТЕБСКАЯ обл,"54,53907","30,44640"
4,"Минская обл, Борисов г., Гагарина ул., д. 107","Минская обл, Борисовский р-н, Борисов г., Гага...",Борисов г.,Минская обл,"54,20665","28,48617"
5,"""Минская обл, Борисов г., Труда ул., дом № 2, ...",NaN,NaN,NaN,NaN,NaN
6,"""Минская обл, Червенский р-н, Турец аг., Юбиле...",NaN,NaN,NaN,NaN,NaN
7,"Минская обл, Смолевичский р-н, Смолевичи г., П...","Минская обл, Смолевичский р-н, Смолевичи г., П...",Смолевичский р-н,Минская обл,"54,02913","28,09104"
8,"""Минская обл, Березино г., Купалы Я. ул., д. 1...",NaN,NaN,NaN,NaN,NaN
9,"""Минская обл, Логойск г., Народная ул., дом № ...",NaN,NaN,NaN,NaN,NaN

In [66]:
place["Магазин"][0].split("~")

['"Минская обл,  Воложин г., Советская ул., д. 95, магазин ""Евроопт"""',
 '"Минская обл, Воложинский р-н, Воложин г., Советская ул., д. 95, магазин ""Евроопт"""',
 'Воложин г.',
 'Минская обл',
 '54,09234',
 '26,52094']

In [67]:
for i in range(place.shape[0]):
    if place.iloc[i]["Адрес"] is np.nan:
        place.iloc[i] = place.iloc[i]["Магазин"].split("~")

In [68]:
place

,Магазин,Адрес,Регион,Область,Широта,Долгота
0,"""Минская обл, Воложин г., Советская ул., д. 9...","""Минская обл, Воложинский р-н, Воложин г., Сов...",Воложин г.,Минская обл,"54,09234","26,52094"
1,"""Минск г., Пушкина пр., д. 3А, магазин """"Евроо...","Минск г., Пушкина пр., д. 3А",Минск г.,Минская обл,"53,89668","27,49594"
2,"""Минск г., Ольшевского ул., дом № 20 пом.2, ма...","Минск г., Ольшевского ул., дом № 20 пом.2",Минск г.,Минская обл,"53,91738","27,50212"
3,"Витебская обл, Орша г., Ленина ул., дом № 230Ю...","Витебская обл, Орша г., Ленина ул., дом № 230Ю",Орша г.,ВИТЕБСКАЯ обл,"54,53907","30,44640"
4,"Минская обл, Борисов г., Гагарина ул., д. 107","Минская обл, Борисовский р-н, Борисов г., Гага...",Борисов г.,Минская обл,"54,20665","28,48617"
5,"""Минская обл, Борисов г., Труда ул., дом № 2, ...","Минская обл, Борисов г., Труда ул., дом № 2, м...",Борисов г,Минская обл,"54,22390","28,52969"
6,"""Минская обл, Червенский р-н, Турец аг., Юбиле...","Минская обл, Червенский р-н, Турец аг., Юбилей...",Червенский р-н,Минская обл,"53,66634","28,08086"
7,"Минская обл, Смолевичский р-н, Смолевичи г., П...","Минская обл, Смолевичский р-н, Смолевичи г., П...",Смолевичский р-н,Минская обл,"54,02913","28,09104"
8,"""Минская обл, Березино г., Купалы Я. ул., д. 1...","Минская обл, Березино г., Купалы Я. ул., д. 1/2",Березино г.,Минская обл,"53,83005","28,99065"
9,"""Минская обл, Логойск г., Народная ул., дом № ...","Минская обл, Логойск г., Народная ул., дом № 2Б",Логойск г.,Минская обл,"54,18906","27,84719"

In [101]:
import re
# pattern = r'".([^"]*)".'
pattern = r'".([^"]*)'

for i in range(df.shape[0]):
    find_place = re.findall(pattern, place.iloc[i][0].strip('" '))

    if len(find_place) >= 1:
        # print(find_place[0])
        place["market"][i] = find_place[0]
    else:
        place["market"][i] = ""

In [132]:
place.head(2)

,Магазин,Адрес,Регион,Область,Широта,Долгота,market,longitude,latitude,geo
0,"""Минская обл, Воложин г., Советская ул., д. 9...","""Минская обл, Воложинский р-н, Воложин г., Сов...",Воложин г.,Минская обл,"54,09234","26,52094",Евроопт,26.52094,54.09234,"26.52094,54.09234"
1,"""Минск г., Пушкина пр., д. 3А, магазин """"Евроо...","Минск г., Пушкина пр., д. 3А",Минск г.,Минская обл,"53,89668","27,49594",Евроопт,27.49594,53.89668,"27.49594,53.89668"

In [103]:
def comma_to_dot(field):
    replace_comma2dot = str(field).replace(",", ".")
    return float(replace_comma2dot)


place["longitude"] = place["Долгота"].apply(lambda x: comma_to_dot(x))
place["latitude"] = place["Широта"].apply(lambda x: comma_to_dot(x))

place["geo"] = place["longitude"].astype(str) + "," + place["latitude"].astype(str)

In [107]:
place[["market", "longitude", "latitude", "geo"]]

          market  longitude  latitude                geo
0        Евроопт   26.52094  54.09234  26.52094,54.09234
1        Евроопт   27.49594  53.89668  27.49594,53.89668
2  Хит! Экспресс   27.50212  53.91738  27.50212,53.91738
3                  30.44640  54.53907   30.4464,54.53907
4                  28.48617  54.20665  28.48617,54.20665
5         Грошык   28.52969  54.22390   28.52969,54.2239
6        Евроопт   28.08086  53.66634  28.08086,53.66634
7                  28.09104  54.02913  28.09104,54.02913
8        Евроопт   28.99065  53.83005  28.99065,53.83005
9  Хит! Экспресс   27.84719  54.18906  27.84719,54.18906

In [128]:
for i in range(10):
    pl = place.iloc[i]
    print(
        f"('{pl['market']}', '{pl['Адрес']}', '{pl['Регион']}', '{pl['Область']}', '{pl['geo']}'), "
    )

('Евроопт', '"Минская обл, Воложинский р-н, Воложин г., Советская ул., д. 95, магазин ""Евроопт"""', 'Воложин г.', 'Минская обл', '26.52094,54.09234'),
('Евроопт', 'Минск г., Пушкина пр., д. 3А', 'Минск г.', 'Минская обл', '27.49594,53.89668'),
('Хит! Экспресс', 'Минск г., Ольшевского ул., дом № 20 пом.2', 'Минск г.', 'Минская обл', '27.50212,53.91738'),
('', 'Витебская обл, Орша г., Ленина ул., дом № 230Ю', 'Орша г.', 'ВИТЕБСКАЯ обл', '30.4464,54.53907'),
('', 'Минская обл, Борисовский р-н, Борисов г., Гагарина ул., д. 107', 'Борисов г.', 'Минская обл', '28.48617,54.20665'),
('Грошык', 'Минская обл, Борисов г., Труда ул., дом № 2, магазин Грошык', 'Борисов г', 'Минская обл', '28.52969,54.2239'),
('Евроопт', 'Минская обл, Червенский р-н, Турец аг., Юбилейная ул., д. 16', 'Червенский р-н', 'Минская обл', '28.08086,53.66634'),
('', 'Минская обл, Смолевичский р-н, Смолевичи г., Первомайская ул., д. 1', 'Смолевичский р-н', 'Минская обл', '28.09104,54.02913'),
('Евроопт', 'Минская обл, Березино г., Купалы Я. ул., д. 1/2', 'Березино г.', 'Минская обл', '28.99065,53.83005'),
('Хит! Экспресс', 'Минская обл, Логойск г., Народная ул., дом № 2Б', 'Логойск г.', 'Минская обл', '27.84719,54.18906'),